web:
  build: .
  ports:
    - "80:80"
  links:
    - mysql
    - redis
  env_file:
    - env
  volumes:
    - ./src:/var/www/htdocs
mysql:
  image: mysql:5.6.23
  env_file:
    - env
redis:
  image: redis:2.8.23

