web:
  image: elzekool/magdev
  ports:
    - "127.0.0.1:80:80"
  links:
    - mysql
    - redis
  env_file:
    - env
  volumes:
    - ./src:/var/www/htdocs
mysql:
  image: mysql:5.6.23
  env_file:
    - env
  ports:
    - "127.0.0.1:13306:3306"
redis:
  image: redis:2.8.23

